### PR TITLE
add module exports

### PR DESCRIPTION
**Pull request by ArturMkrtchyan2399**

### CODE REVIEW

**Comment by wooorm** [comment]
ESM here is intentional. See: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by ArturMkrtchyan2399** [comment]
but it was not helping me

**Comment by ArturMkrtchyan2399** [comment]
i want in my project use metaphone but i cant require it

**Comment by wooorm** [comment]
Please read the resource.

**Comment by ArturMkrtchyan2399** [comment]
i use 
import metaphone from 'metaphone' but it does not work

**Comment by wooorm** [comment]
It seems you did not read the resource, even though I’ve asked 3 times already. Last chance: read it, and if you have specific questions I might be able to help you, but if you don’t show any interest, I’ll lock this conversation.

**Comment by ArturMkrtchyan2399** [comment]
please merge into master if you can

**Pull request closed without merging**
